# Dockerfile
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

ARG PORT=7000
ENV PORT=${PORT}

# These ARGs/ENVs should be set via GitHub Secrets in CI/CD, not hardcoded
ARG JIRA_EMAIL
ARG JIRA_API_TOKEN
ARG CONFLUENCE_EMAIL
ARG CONFLUENCE_API_TOKEN
ARG JIRA_URL=https://example.atlassian.net
ARG CONFLUENCE_URL=https://example.atlassian.net/wiki

ENV JIRA_EMAIL=$JIRA_EMAIL
ENV JIRA_API_TOKEN=$JIRA_API_TOKEN
ENV CONFLUENCE_EMAIL=$CONFLUENCE_EMAIL
ENV CONFLUENCE_API_TOKEN=$CONFLUENCE_API_TOKEN
ENV JIRA_URL=$JIRA_URL
ENV CONFLUENCE_URL=$CONFLUENCE_URL

EXPOSE ${PORT}

CMD ["node", "server.js"]
