name: Build & Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract project name
        id: project
        run: echo "REPO=atlassian-gpt-proxy" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            --build-arg JIRA_EMAIL=${{ secrets.JIRA_EMAIL }} \
            --build-arg JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }} \
            --build-arg CONFLUENCE_EMAIL=${{ secrets.CONFLUENCE_EMAIL }} \
            --build-arg CONFLUENCE_API_TOKEN=${{ secrets.CONFLUENCE_API_TOKEN }} \
            -t ${{ secrets.DOCKER_USERNAME }}/$REPO:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/$REPO:latest
